kind: Service                             
apiVersion: v1
metadata:
  name: jackvector
  labels:
    app: jackvector
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: jackvector                    
  type: LoadBalancer  